messages:

  xml:
    fields:
      - name: "xmlField1"
        type: "String"
        length: 10
        required: true
      - name: "xmlField2"
        type: "Integer"
        length: 5
        required: false

  soap:
    fields:
      - name: "soapField1"
        type: "String"
        length: 10
        required: true
      - name: "soapField2"
        type: "Integer"
        length: 5
        required: false

  json:
    fields:
      - name: "jsonField1"
        type: "String"
        length: 10
        required: true
      - name: "jsonField2"
        type: "Integer"
        length: 5
        required: false